const WHATSAPP='5514998471171';
const models=[
{id:'advocacia',name:'Site para Advocacia',brand:'MODELO PARA ADVOCACIA',category:'Serviços',tag:'SÓBRIO & ELEGANTE',bg:'#e8e2d8',site:'#172526',ink:'#f4eee3',accent:'#c6a974',button:'#152523',symbol:'§',headline:'Segurança para suas decisões.',desc:'Uma presença sóbria para apresentar áreas de atuação e facilitar o primeiro contato.',copy:'Orientação jurídica com clareza e atenção em cada etapa.',services:['Áreas de atuação','Sobre o escritório','Atendimento'],cta:'Conheça o escritório'},
{id:'clinica',name:'Site para Clínica',brand:'MODELO PARA CLÍNICA',category:'Saúde e beleza',tag:'LEVE & ACOLHEDOR',bg:'#e2eae7',site:'#f5faf7',ink:'#294a40',accent:'#527f6a',symbol:'+',headline:'Cuidado que começa com você.',desc:'Apresente a clínica, os profissionais e as especialidades em um visual acolhedor.',copy:'Atenção à sua saúde em um ambiente pensado para acolher.',services:['Especialidades','Nossa equipe','Contato'],cta:'Conheça a clínica'},
{id:'barbearia',name:'Site para Barbearia',brand:'MODELO PARA BARBEARIA',category:'Saúde e beleza',tag:'URBANO & MARCANTE',bg:'#dddfe2',site:'#17181b',ink:'#f5f2ec',accent:'#c6a374',button:'#17181b',symbol:'✂',headline:'Seu estilo. Nossa assinatura.',desc:'Um modelo marcante para valorizar seus serviços, sua equipe e seu espaço.',copy:'Tradição e estilo em cada detalhe do seu atendimento.',services:['Corte & barba','Nosso espaço','Fale com a equipe'],cta:'Conheça os serviços'},
{id:'seguros',name:'Site para Corretora de Seguros',brand:'MODELO PARA SEGUROS',category:'Serviços',tag:'CONFIANÇA & CLAREZA',bg:'#e0e8f2',site:'#f7faff',ink:'#173252',accent:'#2e6aae',symbol:'◇',headline:'Sua tranquilidade tem valor.',desc:'Organize as coberturas e destaque o atendimento de sua corretora.',copy:'Proteção para o que importa, em cada fase da sua vida.',services:['Para você','Para sua empresa','Atendimento'],cta:'Explore as coberturas'},
{id:'restaurante',name:'Site para Restaurante',brand:'MODELO PARA RESTAURANTE',category:'Gastronomia',tag:'SABOR & PERSONALIDADE',bg:'#f2dfd3',site:'#fdf5ed',ink:'#542b1e',accent:'#a4472b',symbol:'◉',headline:'Bons momentos começam à mesa.',desc:'Valorize o cardápio, a história do restaurante e as informações para visitar.',copy:'Ingredientes selecionados. Receitas para compartilhar.',services:['Nosso cardápio','Nossa história','Venha nos visitar'],cta:'Conheça o cardápio'},
{id:'imoveis',name:'Site para Imobiliária',brand:'MODELO PARA IMOBILIÁRIA',category:'Serviços',tag:'CONTEMPORÂNEO & LIMPO',bg:'#dce4ed',site:'#eef3f7',ink:'#223747',accent:'#526d82',symbol:'⌂',headline:'Um novo lugar para chamar de seu.',desc:'Um ponto de partida para apresentar sua imobiliária e imóveis em destaque.',copy:'Encontre possibilidades para a sua próxima mudança.',services:['Em destaque','Nossa imobiliária','Converse conosco'],cta:'Explore possibilidades'},
{id:'loja',name:'Site para Loja de Moda',brand:'MODELO PARA LOJA DE MODA',category:'Comércio',tag:'EDITORIAL & PREMIUM',bg:'#ebe3df',site:'#f5efea',ink:'#423830',accent:'#967c69',symbol:'✦',headline:'Detalhes que fazem o seu estilo.',desc:'Uma vitrine de marca para apresentar coleções e levar o cliente ao atendimento.',copy:'Peças escolhidas para os momentos que são seus.',services:['Coleções','Nossa curadoria','Atendimento'],cta:'Veja a coleção'},
{id:'estetica',name:'Site para Estética',brand:'MODELO PARA ESTÉTICA',category:'Saúde e beleza',tag:'DELICADO & SOFISTICADO',bg:'#eae0e9',site:'#fbf5fa',ink:'#593c52',accent:'#a47591',symbol:'❋',headline:'Sua melhor versão começa aqui.',desc:'Dê destaque aos tratamentos e ao atendimento com um visual delicado.',copy:'Um espaço de cuidado, bem-estar e atenção aos detalhes.',services:['Tratamentos','Nosso espaço','Tire suas dúvidas'],cta:'Explore os tratamentos'},
{id:'servicos',name:'Site para Serviços Empresariais',brand:'MODELO PARA SERVIÇOS',category:'Serviços',tag:'DIRETO & VERSÁTIL',bg:'#dce7ef',site:'#102336',ink:'#f3f7fc',accent:'#f78044',symbol:'↗',headline:'Boas soluções movem seu negócio.',desc:'Apresente sua empresa, seus diferenciais e serviços de forma direta.',copy:'Experiência e compromisso para acompanhar seu próximo passo.',services:['Nossos serviços','Quem somos','Entre em contato'],cta:'Conheça as soluções'}
];
const cards=document.querySelector('#cards');let filter='Todos',query='',selected=null;
function normalize(s){return s.normalize('NFD').replace(/[\u0300-\u036f]/g,'').toLowerCase()}
function render(){const results=models.filter(m=>(filter==='Todos'||filter===m.category)&&normalize(m.name+' '+m.category+' '+m.desc).includes(normalize(query)));cards.innerHTML=results.map(m=>`<article class="card"><a class="preview-photo" href="modelos/${m.id}/index.html" aria-label="Ver demonstração de ${m.name}" style="--card-accent:${m.accent}"><img src="modelos/${m.id}/assets/hero.webp" alt="Imagem ilustrativa do modelo ${m.name}" loading="lazy"><span class="model-label">${m.tag}</span><div class="photo-caption"><span>${m.brand}</span><strong>${m.headline}</strong></div></a><div class="card-body"><div class="card-meta"><span>${m.category.toUpperCase()}</span><span>PERSONALIZÁVEL</span></div><h3>${m.name}</h3><p>${m.desc}</p><div class="card-bottom"><div class="card-price"><small>A PARTIR DE</small><strong>R$ 800</strong></div><a class="demo-button" href="modelos/${m.id}/index.html">Ver demonstração</a></div><button class="choose-button" data-id="${m.id}">Escolher este modelo</button></div></article>`).join('');document.querySelector('#empty').hidden=results.length>0;cards.querySelectorAll('.choose-button').forEach(b=>b.addEventListener('click',()=>chooseModel(b.dataset.id)))}
const proposal=document.querySelector('#proposal-dialog');
function chooseModel(id){selected=models.find(m=>m.id===id);if(!selected)return;document.querySelector('#proposal-form').reset();document.querySelector('#selected-name').textContent=selected.name;document.querySelector('#proposal-form').hidden=false;document.querySelector('#brief-result').hidden=true;document.querySelector('#copy-status').textContent='';proposal.showModal()}
document.querySelectorAll('[data-filter]').forEach(b=>b.addEventListener('click',()=>{filter=b.dataset.filter;document.querySelectorAll('[data-filter]').forEach(x=>{x.classList.toggle('active',x===b);x.setAttribute('aria-pressed',x===b)});render()}));
document.querySelector('#search').addEventListener('input',e=>{query=e.target.value;render()});document.querySelectorAll('.close').forEach(b=>b.addEventListener('click',()=>b.closest('dialog').close()));document.querySelectorAll('dialog').forEach(d=>d.addEventListener('click',e=>{if(e.target===d){const r=d.getBoundingClientRect();if(e.clientX<r.left||e.clientX>r.right||e.clientY<r.top||e.clientY>r.bottom)d.close()}}));
document.querySelector('#proposal-form').addEventListener('submit',e=>{e.preventDefault();const f=new FormData(e.target);document.querySelector('#brief').value=`Olá, Vitrine Certa! Tenho interesse em um site.\n\nModelo: ${selected.name}\nEmpresa: ${f.get('empresa')}\nO que preciso: ${f.get('necessidade')||'Gostaria de conversar sobre o projeto.'}\n\nVi o valor inicial de R$ 800 e gostaria de alinhar o escopo e receber o orçamento.`;e.target.hidden=true;document.querySelector('#whatsapp-brief').href='https://wa.me/'+WHATSAPP+'?text='+encodeURIComponent(document.querySelector('#brief').value);document.querySelector('#brief-result').hidden=false});document.querySelector('#copy-brief').addEventListener('click',async()=>{const text=document.querySelector('#brief');try{await navigator.clipboard.writeText(text.value);document.querySelector('#copy-status').textContent='Pedido copiado. Agora você pode compartilhar.'}catch{text.focus();text.select();document.querySelector('#copy-status').textContent='Selecione e copie o pedido para compartilhar.'}});render();const requested=new URLSearchParams(window.location.search).get('modelo');if(requested)chooseModel(requested);
